config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'

  resources :stores do
    resources :items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_items  #, only: [:index, :show, :edit, :update, :destroy]


  def index
    # @store = Store.find(params[:store_id])
    @items = @store.items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = @store.items.new
    render partial: "form"
  end

  def create
    @item = @store.items.new(item_params)

    if @item.save
      redirect_to store_item_path(@store, @item)
    else
      render :new
    end
  end

  def edit
    @item = @store.items.find(params[:id])
    render partial: "form"
  end

  def update
    @item = @store.items.find(params[:id])

    if @item.update(item_params)
      redirect_to store_item_path(@store, @item)
    else
      render :edit
    end
  end

    def destroy
      @item = @store.items.find(params[:id])
      @item.destroy
      redirect_to store_path(@store)
    end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end

  def set_items
    @store = Store.find(params[:store_id])
  end

  def redirect_item
    redirect_to store_item_path(@store, @item)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  
  def index
    @stores = Store.all
  end

  def show
   # @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
    render partial: "form" 

  end

  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to stores_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

 def update
    if @store.update(store_params)
      redirect_to store_path
    else
      render :edit
    end
  end

def destroy
  @store.destroy
  redirect_to stores_path
end

  private

  def store_params
    params.require(:store).permit(:name)
  end

  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create New Item' %></h1>
<hr />

<%= form_for [@store, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>

  
<% end %>

<%= link_to 'Back', @item.id ? store_item_path(@store, @item) : store_path(@store)%>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1><%= @store.name %></h1>


<%= link_to 'Add a new item to inventory', new_store_item_path(@store) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@store, item] %></li>
  <% end %>
</ul>

<%= link_to 'Back', store_path(@store)%>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @store.name %> - <%= @item.name %> </h1>
<hr />
<p>What would you like to do?</p>
  <br />
<%= link_to 'Edit Item', edit_store_item_path(@store, @item) %>
<br />
<%= link_to 'Delete this Item', [@store, @item], method: :delete %>
<br />

<%= link_to 'Back', store_path(@store)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<h1><%= @store.id ? 'Edit Store' : 'Create Store' %></h1>
<hr />
<%= form_for @store do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/stores/index.html.erb
<h1>Click a Store to view items</h1>
<%= link_to 'Create a new store department', new_store_path %>
<ul>
  <% @stores.each do |s| %>
    <li><%= link_to s.name, s %></li>
    <%= s.description %>
    
  <% end %>
</ul>

app/views/stores/new.html.erb
new

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Items in that store', store_items_path(@store) %>
<br />
<%= link_to 'Edit Store', edit_store_path(@store) %>
<br />
<%= link_to 'Delete Store', @store, method: :delete %>
<br />
<br />

<%= link_to 'Back', stores_path%>